spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    properties:
      jakarta:
        persistence:
          jdbc:
            url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
            username: ${PGUSER}
            password: ${PGPASSWORD}
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true  